name: CD - Create Release

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: c-hive/gha-yarn-cache@v1

      - name: Install node modules
        run: yarn install

      - name: Run test
        run: yarn test
